# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rwandan Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: production
remotedatabaseurl: "https://sustainabledevelopment-rwanda.github.io/sdg-data-prod"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_data:
  - data: meta
    json: 'https://sustainabledevelopment-rwanda.github.io/sdg-data-prod/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://sustainabledevelopment-rwanda.github.io/sdg-data-prod/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://sustainabledevelopment-rwanda.github.io/sdg-data-prod/meta/schema.json'

analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: sustainabledevelopment@example.com
  suggestions: sustainabledevelopment@example.com
  functional: sustainabledevelopment@example.com
###################################################################################################

# Github Repo for Data
repo_name: sdg-data
branch: develop
org_name: Sustainable Development Rwanda

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Rwanda
  adjective: Rwandan

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true
